# Generated by Django 2.1.5 on 2019-02-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.IntegerField(choices=[(0, 'Mobile'), (1, 'Home'), (2, 'Private')], default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number_type',
            field=models.IntegerField(choices=[(0, 'Mobile'), (1, 'Home'), (2, 'Work'), (3, 'Private'), (4, 'FAX')], default=0),
        ),
    ]
